name: weather_now
description: "A new Flutter project."
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  cupertino_icons: ^1.0.8
  geolocator: ^13.0.1
  weather: ^3.1.1
  intl: ^0.19.0
  equatable: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
